#cloud-config
write_files:
  - path: /opt/id_rsa
    owner: root:root
    permissions: "0600"
    content: |
      ${indent(6, private_key)}
  - path: /opt/id_rsa.pub
    owner: root:root
    permissions: "0600"
    content: ${public_key}
packages:
  - python3-pip
  - jq
runcmd:
  - mv /opt/id_rsa* /home/${ssh_user}/.ssh/
  - chown ${ssh_user}:${ssh_user} /home/${ssh_user}/.ssh/id_rsa
  - chown ${ssh_user}:${ssh_user} /home/${ssh_user}/.ssh/id_rsa.pub
  - pip3 install ansible==2.9.9
  - pip3 install netaddr==0.7.19